// Unit tests for src/parser.worker.js — provider detection + genotype
// extraction for both 23andMe (4-col) and AncestryDNA (5-col) layouts.
//
// Run with: node tests/parser.test.mjs   (or: make parser-test)
//
// The worker is designed to run in a browser Web Worker scope (it references
// `self.onmessage` / `self.postMessage` at module top level). To exercise it
// in Node without altering its contract, we load the source as text and run
// it inside a vm sandbox that exposes a fake `self` matching the Worker API.
// The driver then `postMessage`s a parse request and captures the reply,
// exactly as src/main.js does at runtime.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const WORKER_SRC = readFileSync(join(ROOT, "src/parser.worker.js"), "utf8");

// ─── Worker harness ──────────────────────────────────────────────────────────
// Build a fresh sandbox per parse call so onmessage state can't leak between
// tests. Returns the single response posted back by the worker.
function runWorker(fileText) {
  let onmessage = null;
  const posted = [];
  const fakeSelf = {
    set onmessage(fn) { onmessage = fn; },
    get onmessage() { return onmessage; },
    postMessage: (msg) => posted.push(msg),
  };
  const context = { self: fakeSelf };
  vm.createContext(context);
  vm.runInContext(WORKER_SRC, context, { filename: "parser.worker.js" });
  if (typeof onmessage !== "function") {
    throw new Error("worker did not register self.onmessage");
  }
  onmessage({ data: { type: "parse", fileText } });
  if (posted.length !== 1) {
    throw new Error(`expected 1 postMessage, got ${posted.length}`);
  }
  return posted[0];
}

// ─── Test runner ─────────────────────────────────────────────────────────────
let pass = 0;
let fail = 0;
const failures = [];

function assert(name, condition, detail = "") {
  if (condition) {
    pass++;
    process.stdout.write(`  ✓ ${name}\n`);
  } else {
    fail++;
    failures.push(`✗ ${name}${detail ? `\n    ${detail}` : ""}`);
    process.stdout.write(`  ✗ ${name}\n`);
  }
}

function section(title) {
  process.stdout.write(`\n${title}\n`);
}

// ─── Synthetic fixtures ──────────────────────────────────────────────────────
// The same biological genotype calls expressed in each provider's layout.
// Includes: all 10 target rsIDs, an off-target row (to verify filtering),
// one explicit no-call per provider, one indel-style no-call (DD/II), and
// one missing target (rs1142345 omitted entirely → should be absent from
// the output map, contributing to "not determined" downstream).

const COMMON_EXPECTED = {
  rs4244285:  "GA",
  rs4986893:  "GG",
  rs12248560: "CT",
  rs1799853:  "CC",
  rs1057910:  "AA",
  rs9923231:  "CT",
  rs4149056:  "TC",
  rs1800462:  "CC",
  rs1800460:  "GG",
  // rs1142345 intentionally absent (no-call in fixtures).
};

const TWENTYTHREE_FIXTURE = [
  "# This data file generated by 23andMe at: Sat Jun 20 11:00:00 2026",
  "# https://you.23andme.com/p/yourname/tools/data/",
  "# rsid\tchromosome\tposition\tgenotype",
  "rs3094315\t1\t752566\tAG",            // off-target, must be ignored
  "rs4244285\t10\t96541616\tGA",
  "rs4986893\t10\t96540410\tGG",
  "rs12248560\t10\t96521657\tCT",
  "rs1799853\t10\t96702047\tCC",
  "rs1057910\t10\t96741053\tAA",
  "rs9923231\t16\t31107689\tCT",
  "rs4149056\t12\t21331549\tTC",
  "rs1800462\t6\t18143955\tCC",
  "rs1800460\t6\t18139228\tGG",
  "rs1142345\t6\t18130687\t--",          // explicit 23andMe no-call
  "rs9999999\t1\t1000000\tII",            // off-target indel, must be ignored
  "",
].join("\n");

const ANCESTRY_FIXTURE = [
  "#AncestryDNA raw data download",
  "#",
  "#This file was generated by AncestryDNA at: 06/20/2026 11:00:00",
  "#Genome build: GRCh37",
  "#rsid\tchromosome\tposition\tallele1\tallele2",
  "rs3094315\t1\t752566\tA\tG",          // off-target, must be ignored
  "rs4244285\t10\t96541616\tG\tA",
  "rs4986893\t10\t96540410\tG\tG",
  "rs12248560\t10\t96521657\tC\tT",
  "rs1799853\t10\t96702047\tC\tC",
  "rs1057910\t10\t96741053\tA\tA",
  "rs9923231\t16\t31107689\tC\tT",
  "rs4149056\t12\t21331549\tT\tC",
  "rs1800462\t6\t18143955\tC\tC",
  "rs1800460\t6\t18139228\tG\tG",
  "rs1142345\t6\t18130687\t0\t0",        // explicit Ancestry per-allele no-call
  "rs9999998\t1\t1000001\tD\tD",          // off-target indel, must be ignored
  "",
].join("\n");

// ─── 1. 23andMe parsing ──────────────────────────────────────────────────────
section("23andMe fixture");
{
  const reply = runWorker(TWENTYTHREE_FIXTURE);
  assert(
    "reply type is 'result'",
    reply.type === "result",
    `got type=${reply.type} msg=${reply.message || ""}`,
  );
  assert(
    "provider detected as 23andMe",
    reply.meta && reply.meta.provider === "23andMe",
    `got provider=${reply.meta && reply.meta.provider}`,
  );
  for (const [rsid, expected] of Object.entries(COMMON_EXPECTED)) {
    assert(
      `${rsid} = ${expected}`,
      reply.genotypes && reply.genotypes[rsid] === expected,
      `got ${reply.genotypes && reply.genotypes[rsid]}`,
    );
  }
  assert(
    "rs1142345 no-call ('--') is absent from output map",
    reply.genotypes && !("rs1142345" in reply.genotypes),
    `got ${reply.genotypes && reply.genotypes.rs1142345}`,
  );
  assert(
    "off-target rs3094315 is filtered out",
    reply.genotypes && !("rs3094315" in reply.genotypes),
  );
  assert(
    "no_call_count incremented for the '--' row",
    reply.meta && reply.meta.no_call_count >= 1,
    `got no_call_count=${reply.meta && reply.meta.no_call_count}`,
  );
}

// ─── 2. AncestryDNA parsing ──────────────────────────────────────────────────
section("AncestryDNA fixture");
{
  const reply = runWorker(ANCESTRY_FIXTURE);
  assert(
    "reply type is 'result'",
    reply.type === "result",
    `got type=${reply.type} msg=${reply.message || ""}`,
  );
  assert(
    "provider detected as AncestryDNA",
    reply.meta && reply.meta.provider === "AncestryDNA",
    `got provider=${reply.meta && reply.meta.provider}`,
  );
  for (const [rsid, expected] of Object.entries(COMMON_EXPECTED)) {
    assert(
      `${rsid} = ${expected}`,
      reply.genotypes && reply.genotypes[rsid] === expected,
      `got ${reply.genotypes && reply.genotypes[rsid]}`,
    );
  }
  assert(
    "rs1142345 per-allele no-call ('0','0') is absent from output map",
    reply.genotypes && !("rs1142345" in reply.genotypes),
    `got ${reply.genotypes && reply.genotypes.rs1142345}`,
  );
  assert(
    "off-target rs3094315 is filtered out",
    reply.genotypes && !("rs3094315" in reply.genotypes),
  );
  assert(
    "no_call_count incremented for the '0','0' row",
    reply.meta && reply.meta.no_call_count >= 1,
    `got no_call_count=${reply.meta && reply.meta.no_call_count}`,
  );
}

// ─── 3. Cross-provider equivalence ───────────────────────────────────────────
section("Cross-provider equivalence");
{
  const a = runWorker(TWENTYTHREE_FIXTURE).genotypes;
  const b = runWorker(ANCESTRY_FIXTURE).genotypes;
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  let allEqual = true;
  const diffs = [];
  for (const k of keys) {
    if (a[k] !== b[k]) {
      allEqual = false;
      diffs.push(`${k}: 23andMe=${a[k]} vs Ancestry=${b[k]}`);
    }
  }
  assert(
    "both providers produce identical genotype maps for matching biology",
    allEqual,
    diffs.join("; "),
  );
}

// ─── 4. Column-count fallback when header lacks brand string ────────────────
section("Provider fallback by column count");
{
  // Header is generic (no '23andMe' / 'AncestryDNA' string). Detection must
  // fall back to column count: 5 cols → AncestryDNA, 4 cols → 23andMe.
  const genericAncestry = [
    "# generic raw export",
    "# rsid\tchromosome\tposition\tallele1\tallele2",
    "rs4244285\t10\t96541616\tG\tA",
  ].join("\n");
  const genericTwentyThree = [
    "# generic raw export",
    "# rsid\tchromosome\tposition\tgenotype",
    "rs4244285\t10\t96541616\tGA",
  ].join("\n");

  const a = runWorker(genericAncestry);
  const t = runWorker(genericTwentyThree);
  assert(
    "5-column fallback → AncestryDNA",
    a.meta && a.meta.provider === "AncestryDNA",
    `got ${a.meta && a.meta.provider}`,
  );
  assert(
    "4-column fallback → 23andMe",
    t.meta && t.meta.provider === "23andMe",
    `got ${t.meta && t.meta.provider}`,
  );
  assert(
    "Ancestry fallback still extracts genotype correctly",
    a.genotypes && a.genotypes.rs4244285 === "GA",
    `got ${a.genotypes && a.genotypes.rs4244285}`,
  );
  assert(
    "23andMe fallback still extracts genotype correctly",
    t.genotypes && t.genotypes.rs4244285 === "GA",
    `got ${t.genotypes && t.genotypes.rs4244285}`,
  );
}

// ─── 5. Unrecognized format must never be silently coerced into a call ──────
// A file whose header names neither vendor AND whose column names don't
// corroborate either known layout must be refused outright — never guessed
// at from column count alone. This is a regression test for a real defect:
// a 5-column "rsid, chromosome, position, ref_allele, alt_allele" annotation
// dump (a plausible shape for a novel/third-party export) used to be silently
// parsed as if it were AncestryDNA's "allele1, allele2" layout. Because
// ref != alt by construction, every single row would read back as a
// confident HETEROZYGOUS carrier call — regardless of the uploader's actual
// DNA — which is exactly the silent-wrong-answer class this product exists
// to prevent (BUILD_SPEC §4: "never silently assume").
section("Unrecognized vendor format is refused, not guessed");
{
  const mysteryVendor = [
    "# MysteryGenomics raw export v1",
    "# rsid\tchromosome\tposition\tref_allele\talt_allele",
    "rs4244285\t10\t96541616\tG\tA", // ref=G, alt=A — NOT the person's genotype
  ].join("\n");

  const reply = runWorker(mysteryVendor);
  assert(
    "unrecognized format is reported as an error, not a result",
    reply.type === "error",
    `got type=${reply.type}, genotypes=${JSON.stringify(reply.genotypes)}`,
  );
  assert(
    "rs4244285 is never assigned a fabricated genotype",
    !reply.genotypes || !("rs4244285" in reply.genotypes),
    `got ${reply.genotypes && reply.genotypes.rs4244285}`,
  );

  // A malformed row inside an otherwise correctly-identified 23andMe file
  // (5 tab fields instead of the expected 4, e.g. a stray trailing column)
  // must not be silently reinterpreted under AncestryDNA's schema — it
  // should read the correct genotype column, ignoring the extra field.
  const strayColumn23andme = [
    "# This data file generated by 23andMe at: Sat Jun 20 11:00:00 2026",
    "# rsid\tchromosome\tposition\tgenotype",
    "rs4244285\t10\t96541616\tGA\tEXTRA", // 5 fields, but this IS a 23andMe file
  ].join("\n");
  const strayReply = runWorker(strayColumn23andme);
  assert(
    "stray extra column in an identified 23andMe file still reads the real genotype",
    strayReply.genotypes && strayReply.genotypes.rs4244285 === "GA",
    `got ${strayReply.genotypes && strayReply.genotypes.rs4244285}`,
  );
}

// ─── Summary ─────────────────────────────────────────────────────────────────
process.stdout.write(`\n${pass} passed, ${fail} failed\n`);
if (fail > 0) {
  process.stdout.write("\n" + failures.join("\n") + "\n");
  process.exit(1);
}
